
  ##User defined Properties:
kafka.reuest.topic: request
kafka.reply.topic: response
kafka.group.id: test-group

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-commit-interval: 50
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      batch-size: 1
      bootstrap-servers: localhost:9092
